INSERT INTO `data_dictionary`(`type`, `code`, `name`, `remark`)
VALUES ('BillCategory', '0', '餐饮', '账单分类'),
       ('BillCategory', '1', '交通', '账单分类'),
       ('BillCategory', '2', '书籍', '账单分类'),
       ('BillCategory', '3', '礼金', '账单分类'),
       ('BillCategory', '4', '住房', '账单分类'),
       ('BillCategory', '5', '通讯', '账单分类'),
       ('BillCategory', '6', '学习', '账单分类'),
       ('BillCategory', '7', '购物', '账单分类'),
       ('BillCategory', '8', '其他', '账单分类'),
       ('BillDimensionCode', 'day', '日统计维度', '账单统计维度'),
       ('BillDimensionCode', 'month', '月统计维度', '账单统计维度'),
       ('BillDimensionCode', 'year', '年统计维度', '账单统计维度'),
       ('BillIndicatorCode', 'sum', '消费金额总和', '账单统计指标'),
       ('BillIndicatorCode', 'min', '最小消费金额', '账单统计指标'),
       ('BillIndicatorCode', 'max', '最大消费金额', '账单统计指标'),
       ('BillIndicatorCode', 'avg', '平均消费金额', '账单统计指标');