# spring config
spring.application.name=dsb
server.port=9826
server.servlet.context-path=/dsb
server.tomcat.uri-encoding=UTF-8
spring.main.allow-bean-definition-overriding=true

# mysql client config
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/digital_second_brain?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
spring.datasource.username=ENC(ZjqB927VrbEp0BUANaj5YQ==)
spring.datasource.password=ENC(SaDGNwIZTSaq0sWy80bqTA==)

# redis client config
spring.data.redis.host=127.0.0.1
spring.data.redis.password=ENC(gSZMLWuvAIt47uR4ir5FETkKm15pchjl)
spring.data.redis.port=6379
spring.data.redis.database=0
spring.data.redis.timeout=3000

# swagger switch
swagger.enable=true

# mybatis-plus config
# XML file path
mybatis-plus.mapper-locations=classpath*:mybatis/*.xml
# print SQL statement
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# Specify the encryption key;
# in the production environment, remove this configuration item and instead pass it as a startup parameter
jasypt.encryptor.password=
# specify decryption algorithm
jasypt.encryptor.algorithm=
# specify initialization vector type
jasypt.encryptor.ivGeneratorClassname=org.jasypt.iv.NoIvGenerator

# weather api config
thirdparty.weather.service-name=thirdparty-weather
thirdparty.weather.url=http://wthrcdn.etouch.cn

